name: Run Booking Items Update

on:
  schedule:
    - cron: "0 1,6,9 * * *"  # Runs at 1 AM, 6 AM, and 9 AM UTC (which is 8 AM, 1 PM, and 4 PM in GMT+7)
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  trigger-api:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to API
        run: |
          curl -X POST ${{ secrets.UPDATE_SHEET_API_URL }}
